apiVersion: v1
kind: Service
metadata:
  name: user-profile-service-db
spec:
  selector:
    app: user-profile-service-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
