apiVersion: v1
kind: Service
metadata:
  name: user-profile-service
spec:
  selector:
    app: user-profile-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP